In [1]:
#Installing the numpy module
#pip install numpy 

In [2]:
import numpy as np 

## Creating arrays from a list

In [3]:
#One dimensional array or vector
myList = [1,2,3,4,5]
np.array(myList)

array([1, 2, 3, 4, 5])

In [4]:
#Two dimensional array or matrix
myNestedList = [[1,2,3], [4,5,6], [7,8,9]]
np.array(myNestedList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
myList1 = [1, 2, 3]
myList2 = [4, 5, 6]
np.array([myList1, myList2])

array([[1, 2, 3],
       [4, 5, 6]])

## Creating arrays using functions

In [6]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1.shape

(10,)

In [8]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
arr2 = np.zeros((4,6))
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
arr2.shape

(4, 6)

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [14]:
np.full((5,5), 10.5)

array([[10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5]])

## Reshaping Arrays

In [15]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
myArray = np.arange(12)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
myArray.reshape(4, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
myArray.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
myArray.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## Random Arrays

In [24]:
np.random.randn(4,5)

array([[ 0.89964155, -0.11162961, -0.76507088,  0.35458196,  1.25358815],
       [-0.17248395,  0.18050973,  0.75112584,  0.23052526, -0.62738657],
       [-0.34101629, -0.88989326, -0.48922373, -0.16201341,  0.25039863],
       [-1.1572876 ,  0.07139141, -0.7965114 , -0.42611939,  0.45653447]])

In [25]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
myArray[4]

4

In [27]:
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
my2DArray = np.arange(10).reshape(2,5)

In [29]:
my2DArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
my2DArray[1][2]

7

In [31]:
myArray[1:5:2]

array([1, 3])

## Sorting Arrays

In [32]:
unsortedArr = np.array([40, 30, 20, 10, 50])
unsortedArr

array([40, 30, 20, 10, 50])

In [33]:
unsortedArr.sort()
unsortedArr

array([10, 20, 30, 40, 50])

In [34]:
type(unsortedArr)

numpy.ndarray

In [35]:
myArr = np.array([40, 30, 20, 10, 50])
myArr

array([40, 30, 20, 10, 50])

In [36]:
sortedArr = np.array(sorted(myArr))
sortedArr

array([10, 20, 30, 40, 50])

In [37]:
type(sortedArr)

numpy.ndarray

## Broadcasting

In [39]:
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
newArr[:] = 10

In [41]:
newArr

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [42]:
newArr[:5] = 100
newArr

array([100, 100, 100, 100, 100,  10,  10,  10,  10,  10])

In [43]:
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
copiedArr = newArr.copy()
copiedArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
copiedArr[:] = 100
copiedArr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Indexing a Matrix

In [47]:
arr2d = np.arange(25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr2d[1][2]

7

In [49]:
arr2d[1,2]

7

In [50]:
arr2d[:,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

## Conditional Selection

In [52]:
newArr = np.arange(1,11)
newArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
newArr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
newArr[newArr>5]

array([ 6,  7,  8,  9, 10])