In [1]:
#Installing the numpy module
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np 

## Creating arrays from a list

In [3]:
#One dimensional array or vector
myList = [1,2,3,4,5]
np.array(myList)

array([1, 2, 3, 4, 5])

In [4]:
#Two dimensional array or matrix
myNestedList = [[1,2,3], [4,5,6], [7,8,9]]
np.array(myNestedList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
myList1 = [1, 2, 3]
myList2 = [4, 5, 6]
np.array([myList1, myList2])

array([[1, 2, 3],
       [4, 5, 6]])

## Creating arrays using functions

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [16]:
np.full((5,5), 10.5)

array([[10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5]])