In [2]:
#Installing the numpy module
#pip install numpy 

In [3]:
import numpy as np 

## Creating arrays from a list

In [4]:
#One dimensional array or vector
myList = [1,2,3,4,5]
np.array(myList)

array([1, 2, 3, 4, 5])

In [5]:
#Two dimensional array or matrix
myNestedList = [[1,2,3], [4,5,6], [7,8,9]]
np.array(myNestedList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
myList1 = [1, 2, 3]
myList2 = [4, 5, 6]
np.array([myList1, myList2])

array([[1, 2, 3],
       [4, 5, 6]])

## Creating arrays using functions

In [14]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1.shape

(10,)

In [8]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
arr2 = np.zeros((4,6))
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr2.shape

(4, 6)

In [11]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [13]:
np.full((5,5), 10.5)

array([[10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5],
       [10.5, 10.5, 10.5, 10.5, 10.5]])

## Reshaping Arrays

In [18]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
myArray = np.arange(12)
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
myArray.reshape(4, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
myArray.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
myArray.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## Random Arrays

In [29]:
np.random.randn(4,5)

array([[ 1.87053454e-01, -6.53549322e-01,  3.83024596e-01,
         5.26370835e-01, -1.60890645e+00],
       [-1.02188436e+00,  1.70091619e-01, -1.79755615e-01,
        -7.89893098e-01,  7.91603166e-02],
       [ 1.47254436e-01,  8.60961425e-01,  5.22571309e-01,
        -6.20830961e-01,  7.15689505e-01],
       [-1.55014441e+00, -1.01762155e-03,  1.02846804e+00,
        -1.18305384e+00,  9.86307312e-02]])

In [30]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
myArray[4]

4

In [32]:
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
my2DArray = np.arange(10).reshape(2,5)

In [34]:
my2DArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
my2DArray[1][2]

7

In [38]:
myArray[1:5:2]

array([1, 3])

## Sorting Arrays

In [39]:
unsortedArr = np.array([40, 30, 20, 10, 50])
unsortedArr

array([40, 30, 20, 10, 50])

In [40]:
unsortedArr.sort()
unsortedArr

array([10, 20, 30, 40, 50])

In [41]:
type(unsortedArr)

numpy.ndarray

In [43]:
myArr = np.array([40, 30, 20, 10, 50])
myArr

array([40, 30, 20, 10, 50])

In [47]:
sortedArr = np.array(sorted(myArr))
sortedArr

array([10, 20, 30, 40, 50])

In [48]:
type(sortedArr)

numpy.ndarray